# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
