# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_nm', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=8)),
                ('session_code', models.CharField(max_length=100)),
            ],
        ),
    ]
