# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0002_auto_20170704_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Problem_TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testin', models.CharField(max_length=1000)),
                ('testout', models.CharField(max_length=1000)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='problem_testcase',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compile_run.Problem'),
        ),
        migrations.AddField(
            model_name='problem_testcase',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compile_run.TestCase'),
        ),
        migrations.AddField(
            model_name='problem_submission',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compile_run.Problem'),
        ),
        migrations.AddField(
            model_name='problem_submission',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compile_run.Submission'),
        ),
    ]
