# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0004_auto_20170704_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_problem',
            old_name='problem',
            new_name='Problem',
        ),
    ]
