# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0005_auto_20170704_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='Problem',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problem_id',
            new_name='Problem',
        ),
    ]
