# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0007_auto_20170704_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='success_sub',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tot_sub',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='sub_cnt',
            field=models.IntegerField(),
        ),
    ]
