# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0008_auto_20170704_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
