# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0009_problem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem',
            name='c_session_code',
            field=models.CharField(default='#include<stdio.h>', max_length=1000),
            preserve_default=False,
        ),
    ]
