# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0010_user_problem_c_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem',
            name='current_session_code',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
