# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0011_user_problem_current_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_problem',
            name='c_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='cpp_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='current_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='java_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='py_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
