# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0013_remove_user_problem_current_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='temp_c_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='temp_cpp_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='temp_java_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='temp_py_session_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
