# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0014_auto_20170709_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='temp_c_session_code',
            new_name='session_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='temp_cpp_session_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='temp_java_session_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='temp_py_session_code',
        ),
    ]
