# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170710_2325'),
        ('Compile_run', '0017_auto_20170710_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_session_code', models.CharField(max_length=1000, null=True)),
                ('cpp_session_code', models.CharField(max_length=1000, null=True)),
                ('java_session_code', models.CharField(max_length=1000, null=True)),
                ('py_session_code', models.CharField(max_length=1000, null=True)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Problem')),
            ],
        ),
    ]
