# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0018_problem_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='Problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='User',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
