# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0019_auto_20170724_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
