# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0020_user_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
