# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0021_user_problem_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_problem',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
