# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0022_auto_20170726_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_session',
            name='c_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem_session',
            name='cpp_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem_session',
            name='java_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem_session',
            name='py_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testout',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='c_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='cpp_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='java_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_problem',
            name='py_session_code',
            field=models.TextField(null=True),
        ),
    ]
