# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0023_auto_20170726_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_session',
            name='py3_session_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_problem',
            name='py3_session_code',
            field=models.TextField(null=True),
        ),
    ]
