# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0024_auto_20170729_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem',
            name='last_lang',
            field=models.CharField(default=b'c', max_length=10),
        ),
    ]
