# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compile_run', '0025_user_problem_last_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.IntegerField(default=2)),
                ('cpp_time', models.IntegerField(default=2)),
                ('java_time', models.IntegerField(default=5)),
                ('py_time', models.IntegerField(default=2)),
                ('py3_time', models.IntegerField(default=2)),
            ],
        ),
    ]
