# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_mark', models.CharField(max_length=250)),
                ('p_level', models.CharField(max_length=250)),
                ('p_disc', models.CharField(max_length=250)),
                ('p_input', models.CharField(max_length=250)),
                ('p_cons', models.CharField(max_length=250)),
                ('p_output', models.CharField(max_length=250)),
                ('sample_input', models.CharField(max_length=250)),
                ('sample_output', models.CharField(max_length=250)),
                ('exp', models.CharField(max_length=250)),
                ('Contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Contest')),
            ],
        ),
    ]
