# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170710_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='p_mark',
        ),
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='success_sub',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='tot_sub',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
