# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170710_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Con_signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.IntegerField()),
                ('user', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
