# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_con_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_signup',
            name='con_id',
            field=models.CharField(max_length=250),
        ),
    ]
