# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170715_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='con_signup',
            name='con_id',
        ),
        migrations.AddField(
            model_name='con_signup',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Contest'),
            preserve_default=False,
        ),
    ]
