# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170715_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_signup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
