# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170715_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
