# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170723_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='desc',
            new_name='disc',
        ),
    ]
