# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170723_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='success_sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tot_sub',
            field=models.IntegerField(default=0),
        ),
    ]
