# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170723_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='prize',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='scoring',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='exp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='p_disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(),
        ),
    ]
