# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170726_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('sub', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
