# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='s_rate',
            field=models.CharField(default=0.0, max_length=6),
            preserve_default=False,
        ),
    ]
