# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_problem_s_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='r_flag',
            field=models.BooleanField(default=False),
        ),
    ]
