# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171005_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='p_cons',
            field=models.TextField(),
        ),
    ]
