# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('p_id_1', models.IntegerField(default=0)),
                ('p_id_2', models.IntegerField(default=0)),
                ('sub_time', models.TimeField()),
                ('tot_score', models.IntegerField(default=0)),
            ],
        ),
    ]
