# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0002_vvt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vvt',
        ),
    ]
