# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0006_ajay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajay',
        ),
    ]
