# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0008_ajay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=250)),
                ('con_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('org_name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('tag_line', models.CharField(max_length=250)),
                ('disc', models.CharField(max_length=250)),
                ('rules', models.CharField(max_length=250)),
                ('prize', models.CharField(max_length=250)),
                ('scoring', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_mark', models.CharField(max_length=250)),
                ('p_level', models.CharField(max_length=250)),
                ('p_disc', models.CharField(max_length=250)),
                ('p_input', models.CharField(max_length=250)),
                ('p_cons', models.CharField(max_length=250)),
                ('p_output', models.CharField(max_length=250)),
                ('sample_input', models.CharField(max_length=250)),
                ('sample_output', models.CharField(max_length=250)),
                ('exp', models.CharField(max_length=250)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leader.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
