# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0009_contest_problem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('sub_time', models.TimeField()),
                ('tot_score', models.IntegerField(default=0)),
                ('p_id_fus', models.IntegerField(default=0)),
                ('p_id_gandul', models.IntegerField(default=0)),
            ],
        ),
    ]
