# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0011_delete_ajay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cont_1',
        ),
    ]
