# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0017_cont_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cont_1',
            options={'ordering': ['-tot_score', 'sub_time']},
        ),
    ]
