# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0022_cont_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont_1',
            name='sub_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
