# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0026_cont_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont_1',
            name='user',
        ),
        migrations.DeleteModel(
            name='cont_1',
        ),
    ]
