# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0028_cont_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='contest',
        ),
        migrations.AlterField(
            model_name='cont_1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
