# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20170714_1523'),
        ('Leader', '0030_auto_20170719_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.TimeField(auto_now=True)),
                ('tot_score', models.IntegerField(default=0)),
                ('Find_the_largest_element_in_the_array', models.IntegerField(default=0)),
                ('Ask_to_solve', models.IntegerField(default=0)),
                ('Sherlock_power_pc', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'ordering': ['-tot_score', 'sub_time'],
            },
        ),
    ]
