# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170714_1523'),
        ('Leader', '0033_auto_20170719_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.DateTimeField(auto_now=True)),
                ('tot_score', models.IntegerField(default=0)),
                ('Find_Me', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'ordering': ['-tot_score', 'sub_time'],
            },
        ),
        migrations.RemoveField(
            model_name='cont_3',
            name='user',
        ),
        migrations.DeleteModel(
            name='cont_3',
        ),
    ]
