# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0039_cont_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont_1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cont_5',
            name='user',
        ),
        migrations.DeleteModel(
            name='cont_1',
        ),
        migrations.DeleteModel(
            name='cont_5',
        ),
    ]
