# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0042_cont_1_magical_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont_1',
            name='Find_Me',
        ),
        migrations.RemoveField(
            model_name='cont_1',
            name='Find_YOU',
        ),
    ]
