# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0043_auto_20170724_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont_1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sub_cont_1',
            name='Problem',
        ),
        migrations.RemoveField(
            model_name='sub_cont_1',
            name='User',
        ),
        migrations.DeleteModel(
            name='cont_1',
        ),
        migrations.DeleteModel(
            name='Sub_cont_1',
        ),
    ]
