# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0045_cont_1_sub_cont_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_cont_1',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
