# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0047_cont_2_sub_cont_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cont_2',
            old_name='Divisible_Integer',
            new_name='Special_Episodes',
        ),
    ]
