# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0050_cont_4_sub_cont_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont_4',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sub_cont_4',
            name='Problem',
        ),
        migrations.RemoveField(
            model_name='sub_cont_4',
            name='User',
        ),
        migrations.DeleteModel(
            name='cont_4',
        ),
        migrations.DeleteModel(
            name='Sub_cont_4',
        ),
    ]
