# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0053_cont_6_sub_cont_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cont_6',
            old_name='Debugger',
            new_name='Debug_Builder',
        ),
    ]
