# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leader', '0055_cont_7_sub_cont_7'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cont_7',
            old_name='Pekka_in_maze',
            new_name='Pekka_in_Maze',
        ),
    ]
